name: Gerar APK Android

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar código
        uses: actions/checkout@v4

      - name: Configurar Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.35.0"
          channel: stable
          cache: true

      - name: Criar estrutura Flutter
        run: flutter create --project-name controle_financeiro --platforms=android,web .

      - name: Adicionar dependência shared_preferences
        run: flutter pub add shared_preferences

      - name: Instalar dependências
        run: flutter pub get

      - name: Remover teste padrão do Flutter
        run: rm -f test/widget_test.dart

      - name: Analisar projeto
        run: flutter analyze

      - name: Gerar APK
        run: flutter build apk --release

      - name: Salvar APK
        uses: actions/upload-artifact@v4
        with:
          name: controle-financeiro-apk
          path: build/app/outputs/flutter-apk/app-release.apk
