name: Gerar APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar codigo
        uses: actions/checkout@v4

      - name: Configurar Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: '3.35.2'

      - name: Verificar arquivos
        run: |
          echo "Pasta atual:"
          pwd
          echo "Arquivos:"
          ls -la

      - name: Criar projeto Flutter
        run: |
          if [ ! -f pubspec.yaml ]; then
            echo "pubspec.yaml nao encontrado. Criando projeto Flutter..."
            flutter create .
          else
            echo "pubspec.yaml encontrado."
          fi

      - name: Instalar dependencias
        run: flutter pub get

      - name: Verificar Dart
        run: flutter analyze

      - name: Gerar APK
        run: flutter build apk --release

      - name: Disponibilizar APK
        uses: actions/upload-artifact@v4
        with:
          name: controle-financeiro-apk
          path: build/app/outputs/flutter-apk/app-release.apk
