name: Gerar Web

on:
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar codigo
        uses: actions/checkout@v4

      - name: Configurar Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Criar estrutura Flutter
        run: |
          flutter create . --project-name controle_financeiro --platforms=web

      - name: Instalar dependencias
        run: |
          flutter pub add shared_preferences
          flutter pub add intl
          flutter pub get

      - name: Verificar aplicativo
        run: flutter analyze lib

      - name: Gerar Web
        run: |
          flutter build web --release \
            --base-href "/controle-financeiro/"

      - name: Publicar arquivos
        uses: actions/upload-pages-artifact@v3
        with:
          path: build/web

  deploy:
    needs: build
    runs-on: ubuntu-latest

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    permissions:
      pages: write
      id-token: write

    steps:
      - name: Publicar no GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
